config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books do 
    member do
      get :delete
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to books_path
    else
      flash[:alert] = "There was an error creating the book."
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      flash[:alert] = "There was an error updating the book."
      render :edit
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully deleted."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :price, :author, :published_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<table summary="Book form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.text_field(:price) %></td>
  </tr>
  <tr>
    <th>Published Date</th>
    <td>
      <%= f.date_select(:published_date, start_year: 1900, end_year: Date.today.year, prompt: { day: 'Select Day', month: 'Select Month', year: 'Select Year' }) %>
    </td>
  </tr>
</table>

app/views/books/delete.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="book delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>
    <% # url: book_path(@book), method: 'delete' %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books new">
  <h2>Edit a Book</h2>

  <%= form_for(@book) do |f| %>
    <% # url: books_path, method: 'post' %>

    <%= render(partial: "form", locals: {f:f})%>

    <div class="form-buttons">
      <%= f.submit("Edit Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="books index">
  <h2>Books</h2>

    <%= link_to("Add New Book", new_book_path, class: 'action new') %>

  <table class="listing" summary="Task list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>price</th>
      <th>Published Date</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.id %></td>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td>$<%= book.price%></td>
      <td><%= book.published_date%></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
      </td>

    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books new">
  <h2>Add a New Book</h2>

  <%= form_for(@book) do |f| %>

    <%= render partial: "form", locals: { f: f } %>

    <div class="form-buttons">
      <%= f.submit("Add Book") %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="book show">
  <h2>Show Book</h2>

  <div class="actions">
    <%= link_to('Edit', edit_book_path(@book)) %>
    <%= link_to('Delete', delete_book_path(@book)) %>
  </div>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td>$<%= @book.price%></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @book.published_date %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book Collection" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <% flash.each do |key, message| %>
      <div class="flash <%= key %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>